"""Distributed device fabric for JARVIS.

First-class subsystem owning node identity, capability declarations,
lifecycle/trust, presence, policy-gated command routing, and world/spatial
mirroring. See docs/DEVICE_FABRIC.md.
"""

from .android import (
    ANDROID_ADAPTER_VERSION,
    ANDROID_CAPABILITIES,
    ANDROID_DEVICE_TYPES,
    ANDROID_EVENTS,
    ANDROID_PLATFORM,
    COMMAND_QUEUE_MAX,
    COMMAND_TTL_S,
    LOW_BATTERY_PCT,
    PAIRING_CODE_TTL_S,
    PAIRING_MAX_ATTEMPTS,
    PERMISSION_FOR_CAPABILITY,
    PROACTIVE_ANDROID_EVENTS,
    SAFE_COMMANDS,
    AndroidCommandError,
    AndroidError,
    AndroidNodeAdapter,
    PairingError,
    PairingManager,
    PairingState,
    PermissionState,
    QueuedCommand,
    android_message,
    android_telemetry,
    negotiate_capabilities,
    parse_android_message,
    validate_android_event,
    validate_android_metadata,
    validate_command,
    validate_permission_report,
)
from .capabilities import (
    WELL_KNOWN,
    Capability,
    CapabilityError,
    CapabilityRegistry,
    validate_capability_name,
)
from .audit import AUDIT_FILENAME, DeviceAudit
from .approvals import (
    APPROVED,
    CONSUMED,
    DENIED,
    EXPIRED,
    PENDING,
    REVOKED,
    ApprovalError,
    ApprovalStore,
)
from .authz import (
    DeviceGrantStore,
    GrantError,
    validate_grant_actor,
    validate_grant_capability,
)
from .outbox import (
    CommandOutbox,
    OutboxError,
)
from .service import CommandServiceError, DeviceCommandService
from .fabric import DeviceFabric, FabricError
from .identity import (
    AUTH_METHODS,
    AuthContext,
    IdentityError,
    NodeIdentity,
    current_limitation,
    generate_identity,
    require_verified_transport,
)
from .model import (
    CAPABILITY_VERSION,
    DEVICE_TYPES,
    FABRIC_VERSION,
    PROTOCOL_VERSION,
    Device,
    DeviceError,
    LifecycleError,
    LifecycleState,
    TrustState,
    check_transition,
)
from .protocol import FabricMessage, MessageType, ProtocolError, make_error
from .registry import DeviceRegistry, RegistryError, VersionConflict
from .router import DeviceRouter, RoutingError
from .security import FabricSecurityError, audit_record, scrub
from .telemetry import Telemetry, TelemetryError, is_stale
from .transport import (
    InProcessTransport,
    LocalNode,
    Transport,
    TransportError,
    available_transports,
    get_transport,
    register_transport,
)
from .socket_transport import (
    AuthError,
    DeviceAuthenticator,
    FabricServer,
    FramingError,
    ServerPeer,
    SocketTransport,
    decode_frames,
    encode_frame,
    is_verified_transport,
    verified_auth_context,
)

register_transport("socket", SocketTransport)

__all__ = [
    "ANDROID_ADAPTER_VERSION",
    "ANDROID_CAPABILITIES",
    "ANDROID_DEVICE_TYPES",
    "ANDROID_EVENTS",
    "ANDROID_PLATFORM",
    "AUTH_METHODS",
    "COMMAND_QUEUE_MAX",
    "COMMAND_TTL_S",
    "LOW_BATTERY_PCT",
    "PAIRING_CODE_TTL_S",
    "PAIRING_MAX_ATTEMPTS",
    "PERMISSION_FOR_CAPABILITY",
    "PROACTIVE_ANDROID_EVENTS",
    "SAFE_COMMANDS",
    "AndroidCommandError",
    "AndroidError",
    "AndroidNodeAdapter",
    "AuthContext",
    "AuthError",
    "APPROVED",
    "ApprovalError",
    "ApprovalStore",
    "AUDIT_FILENAME",
    "CONSUMED",
    "CommandOutbox",
    "CommandServiceError",
    "DENIED",
    "DeviceCommandService",
    "Capability",
    "CapabilityError",
    "CapabilityRegistry",
    "Device",
    "DeviceAudit",
    "DeviceAuthenticator",
    "DeviceError",
    "DeviceFabric",
    "DeviceGrantStore",
    "DeviceRegistry",
    "DeviceRouter",
    "EXPIRED",
    "FabricError",
    "FabricMessage",
    "FabricSecurityError",
    "FabricServer",
    "FramingError",
    "GrantError",
    "IdentityError",
    "InProcessTransport",
    "LifecycleError",
    "LifecycleState",
    "LocalNode",
    "MessageType",
    "NodeIdentity",
    "OutboxError",
    "PENDING",
    "PairingError",
    "PairingManager",
    "PairingState",
    "PermissionState",
    "ProtocolError",
    "QueuedCommand",
    "RegistryError",
    "REVOKED",
    "RoutingError",
    "ServerPeer",
    "SocketTransport",
    "Telemetry",
    "TelemetryError",
    "Transport",
    "TransportError",
    "VersionConflict",
    "android_message",
    "android_telemetry",
    "audit_record",
    "available_transports",
    "check_transition",
    "current_limitation",
    "decode_frames",
    "encode_frame",
    "generate_identity",
    "get_transport",
    "is_stale",
    "is_verified_transport",
    "make_error",
    "negotiate_capabilities",
    "parse_android_message",
    "register_transport",
    "require_verified_transport",
    "scrub",
    "validate_android_event",
    "validate_android_metadata",
    "validate_capability_name",
    "validate_command",
    "validate_permission_report",
    "verified_auth_context",
]
